name: Auto Generate Hotwords

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python main.py

      - name: Push to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout gh-pages
          cp output/index.html index.html
          git add index.html
          git commit -m "Update hotwords $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push origin gh-pages
